### ISSUE TITLE
请提供ZLERP.Licensing.Client 

### ISSUE THREAD

**Issue by AllanHao** [ifengkou/License#1]
引用ZLERP.Licensing.Client 无效，请提供一下，谢谢

**Comment by booksir** [comment]
> 引用ZLERP.Licensing.Client 无效，请提供一下，谢谢

还提供啥锤子啊，把无效引用去掉，就可以运行了，对了，顺带把图标引用也去了，就完全可以运行了

**Comment by ifengkou** [comment]
很多年没玩C#了，全文搜索已经移除所有该引用，还请见谅！
